### ISSUE TITLE
Code for ensuring the GUI fits the screen seems gone?

### ISSUE THREAD

**Issue by KimNJensen** [kevinhendricks/Access-Aide#1]
These lines in Accessgui.py seems to have disappeared in the latest version(s) (so the okay/cancel get out of reach):

after line 44:
 // make sure our frame actually fits on the users screen
    framewidth = basewidth*2
    frameheight = basewidth*2
    if framewidth > w:
        framewidth = w
    if frameheight > h:
        frameheight = h
    framesize = (framewidth, frameheight)

**Comment by kevinhendricks** [comment]
Just checked, and those lines still exist in github master.  Perhaps the issue is that the prebuilt plugin has older source for some reason?  If so I will fix that and create a new prebuilt release as it should match what is in master exactly?

Thanks for the head's up.

**Comment by kevinhendricks** [comment]
Just created v043 to fix this.  
Thank you for your bug report.
