### ISSUE TITLE
epub:type in the body element 

### ISSUE THREAD

**Issue by KimNJensen** [kevinhendricks/Access-Aide#2]
The latest recommendation - https://idpf.github.io/epub-guides/epub-aria-authoring/  - says (among other things) that:

"Use of the epub:type attribute on the body element is now also strongly discouraged".

So probably that part should be removed in the plugin and the <body> element left without any alterations whatsoever?

**Comment by kevinhendricks** [comment]
The new rules in place already control what true accessibility attributes are allowed where.  That said, they can not retroactively change where epub:type attributes can be used and still say they match the epub 3.0 version rules.

Having to inject a section tag inside the body tag just to hold a section level epub:type is simply ridiculous.  Again, the people controlling the epub v 3.0.2 spec really need to stop changing things for no valid reason as hitting a constantly moving target is for the birds.

I will think about it.

**Comment by KimNJensen** [comment]
I won't ask for more. It's not a pressing issue. In about five years time … when someone actually begin to use epub 3.2 ;o)
