### ISSUE TITLE
How to solve? Status: failed

### ISSUE THREAD

**Issue by ferformaat** [kevinhendricks/Access-Aide#3]
Can I ask here why the plugin (which must be a great tool!) is not working for me? After installation on Mac OS 10.15. 'No tcl.frameworks'... or something. I installed Xcode. I tried to run " tk8.6.11 " and other stuff that I unfortunately don't understand. Should there be an easy way to install? Here is a screen shot
![failed](https://user-images.githubusercontent.com/14897234/114718207-115c7980-9d36-11eb-8a12-410eb73b7f06.png)
I hope I can get a tip or clue.

**Comment by kevinhendricks** [comment]
You have not installed the required packages to fully run Sigil on macOS.

See this part of every Sigil Release Announcement:

```
Mac users should still download and install ActiveState's ActiveTcl 
Community Edition to utilize plugins that use Tk/Tcl GUIs. 
More here.
```

and the link goes to

https://github.com/Sigil-Ebook/Sigil/wiki/Mac-OS-X-Notes

**Comment by ferformaat** [comment]
Wow!. It worked and the magic happened. Thank you very much for the quick reply. (I was struggling for hours) My first impression is that the plug-in works perfect. Good job!
