### ISSUE TITLE
Plugin runner status fails when running on Sigil

### ISSUE THREAD

**Issue by brianagina** [kevinhendricks/Access-Aide#4]
The plugin has been resourceful when editing EPUBs with a lot of images. The GUI interface that appears after initial check by the plugin makes it easier to update the image descriptions within the EPUB. But for a specific EPUB I am testing on Sigil which was originally created using Adobe Indesign 15, the plugin keeps failing. Meaning it doesn't get to the image description GUI.  I want to be able to add the image descriptions for approximately 200 out of the 600 total images using the plugin.
This is the error I get when the plugin runner status reads failed

 File "C:\Program Files\Sigil\plugin_launchers\python\launcher.py", line 142, in launch
    self.exitcode = target_script.run(container)
  File "C:\Users\USER1\AppData\Local\sigil-ebook\sigil\plugins\Access-Aide\plugin.py", line 469, in run
    naltlist = GUIUpdateFromList("Update Alt Text for Each Image", altlist, basewidth)
  File "C:\Users\USER1\AppData\Local\sigil-ebook\sigil\plugins\Access-Aide\accessgui.py", line 38, in GUIUpdateFromList
    ls = updateList(localRoot, title, list, basewidth)
  File "C:\Users\USER1\AppData\Local\sigil-ebook\sigil\plugins\Access-Aide\accessgui.py", line 102, in __init__
    aimg = resize_image_copy(self.basewidth, img)
  File "C:\Users\USER1\AppData\Local\sigil-ebook\sigil\plugins\Access-Aide\accessgui.py", line 33, in resize_image_copy
    return ImageTk.PhotoImage(image.resize((basewidth, newheight), Image.ANTIALIAS))
  File "site-packages\PIL\Image.py", line 1883, in resize
  File "site-packages\PIL\Image.py", line 1905, in resize
ValueError: height and width must be > 0
Error: height and width must be > 0

The error seems to originate from the plugin and not the EPUB. My EPUB lacks javascript, video/audio media elements and MathML. All images have an empty alt attribute. 
What I can change in the EPUB to have the plugin run successfully? 
Can a fix be implemented into the plugin source code soon to correct the issue?

**Comment by kevinhendricks** [comment]
That error message is not from Access-Aide itself but instead from the python PIL module.  It is complaining that an image is missing height and width or that it is set to a non-positive number.

Does your epub include svg images by chance?  Or Images you have set the height or width to 0 or negative?

I would need a copy of the epub to try to track down which Image is the culprit and how to prevent the PIL module error from impacting Access-Aide.

**Comment by brianagina** [comment]
The EPUB does not have svg images. Neither 0 or negative values for height and width style properties. How can I share the publication privately with you?

**Comment by kevinhendricks** [comment]
If you are a member of Mobileread.com, where are Sigil forum's are, you can use its personal mail (pm) feature to send a private message with the link to "KevinH" (me) with a link.

My guess is one of the images is corrupted somehow.

Another approach is to make a copy of the epub and throw out half the chapters from this copy, and if it works, then you can narrow down the problem code/issue to which half of the book.  Using this binary search approach you should quickly be able to narrow it down to the problem image/page and then post only those pieces.

**Comment by kevinhendricks** [comment]
If it is simpler you could e-mail me the epub as an attachment to:
** email address removed to prevent too mush spamming **

**Comment by brianagina** [comment]
Unfortunately I am not a member of Mobileread.com. Emailing will do. 

Your guess could possibly be correct. I tried looking at the images but I could not come to the same conclusion.

Your final approach was very helpful. I will attach the EPUB with most pages removed when sending the email.

**Comment by kevinhendricks** [comment]
By adding some debug output to my own version of the plugin, the culprit image seems to be:

OEBPS/image/1163.png

which is used in all of the files 6-* but not the working 5-7.

Do you have a replacement image or access to an image editing tool that can check for image file corruption?  I will try the same thing from my end.

**Comment by kevinhendricks** [comment]
Perhaps this is a bug in Access Aide after all as the internal dimensions for that image is:
827x1 px

Perhaps when scaling it down to make a thumbnail, the 1px height becomes a fraction that rounds or truncates to 0 which then causes the problem?

I will take a look.

**Comment by kevinhendricks** [comment]
Yes, that was the bug and it was in Access-Aide as the 1px original image when scaled down to fit the allotcated width became truncate to a new height of 0, which caused the problem.

I have a bug fix.  If you are okay editing python code on your machine I can lead you through making the one-line change in accessgui.py

Change line 32 of that accessgui.py file using a simple text editor.  Note whitespace is important in 
python from:

```
    newheight = int((float(imgheight)*float(scalefactor)))
```

to 

```
    newheight = max(int((float(imgheight)*float(scalefactor))), 1)
```

I will also be releasing a fixed version of Access-Aide today.

**Comment by brianagina** [comment]
Yes, that worked!👍
I'll be on the look out for the updated version.
Thanks a lot for the guidance and time to look into it.

**Comment by kevinhendricks** [comment]
Great!  The fixed version has been posted on Mobileread.com in the Sigil Plugins section and is now available in the plugins folder on this site.
Closing this.  Thank you for the test case and helping to improve Acess-Aide.
