### ISSUE TITLE
acces aide dont work

### ISSUE THREAD

**Issue by mediengenossin** [kevinhendricks/Access-Aide#5]
Dear Kevin Hendrick, 
i´ve installed the latest version 054 from github to my sigil installation 1.8.0 on mac os x big sur. 
The Plugin is shown under the plugin-section (used the reccomanded zip file). I´ve also checked the box "integrated python-interpreter" . If i start the plugin (which is also shown with the correct icon on the toolbar) it dont work, here the failure-message:

Status: failed

Traceback (most recent call last):
  File "/Applications/Sigil.app/Contents/plugin_launchers/python/launcher.py", line 141, in launch
    target_script = __import__(script_module)
  File "/Users/anke/Library/Application Support/sigil-ebook/sigil/plugins/Access-Aide/plugin.py", line 24, in <module>
    from accessgui import GUIUpdateFromList
  File "/Users/anke/Library/Application Support/sigil-ebook/sigil/plugins/Access-Aide/accessgui.py", line 16, in <module>
    from PIL import Image, ImageTk
  File "site-packages/PIL/ImageTk.py", line 28, in <module>
  File "tkinter/__init__.py", line 36, in <module>
ImportError: dlopen(/Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_tkinter.cpython-38-darwin.so, 2): Library not loaded: /Library/Frameworks/Tcl.framework/Versions/8.6/Tcl
  Referenced from: /Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_tkinter.cpython-38-darwin.so
  Reason: image not found
Error: dlopen(/Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_tkinter.cpython-38-darwin.so, 2): Library not loaded: /Library/Frameworks/Tcl.framework/Versions/8.6/Tcl
  Referenced from: /Applications/Sigil.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_tkinter.cpython-38-darwin.so
  Reason: image not found

maybe its a known issue and you could help? am i doing wrong? 
python 3 is existing also: /usr/bin/python3.
p.s.: im using the german version of sigil.

greetings, anke

**Comment by kevinhendricks** [comment]
Yes, your macOS machine is missing its Tcl/Tk Frameworks which enable the graphical user interface for python plugins.

So all MacOS users need to install (once) the Tcl.framework and Tk.framework if they want to use Sigil plugins that use the Tk graphical user interface.

This download was free and made available by ActiveState.  There was a link about it on the Sigil releases page with every release.

Unfortunately, just recently ActiveState has decided to withdraw that free version in an attempt to generate more funds by forcing people to try to buy an Enterprise supported version.

So I have built my own TclTk installer for macOS but it is unsigned as my Apple Developer code-signing id  does not include the privileges to code sign installer ".pkg" files as Sigil is an Application that does not need or use an installer ".pkg".

You are welcome to try to install it.  The TclTk_8.6.12.dmg file has been posted on the Sigil 1.8 release page.  You will have to temporarily enable installing it in your MacOS settings.

**Comment by kevinhendricks** [comment]
I just tested my replacement TclTk package and it only works on macOS Mojave and earlier, so that will not help you.

I will try to build something that will work for newer macOS machines and post it today.

Sorry about that ... ActiveState has been making these downloads available for free for a very long time (close to 10 years now) but just decided to stop and so created this issue.

**Comment by kevinhendricks** [comment]
Okay, I now have a fixed TclTk installer that was tested to work with Catalina and above.  It can be downloaded from the official Sigil 1.8.0 Release website here:

https://github.com/Sigil-Ebook/Sigil/releases/tag/1.8.0

**Comment by mediengenossin** [comment]
Dear Kevin,
you have done a great job. good working now, no problems, a great help and WOW-! so speedy!
Have 1000 of thanks! 

Warm Greetings from the cold black forest, 
Anke


Anke Brodersen
Grafik und Gestaltung


Mediengenossen eG   
Guntramstr. 11
D-79106 Freiburg
Tel. 0049.(0)761.88869099
www.mediengenossen.de

**Comment by kevinhendricks** [comment]
Glad to hear it is working.  BTW, my wife's family is German and she has Aunts and Uncles who live not too far away from Freiburg.  We spent one week visiting Freiburg and the area about 5 years ago.  The downtown markets and restaurants were simply wonderful.  What a nice city!

**Comment by mediengenossin** [comment]
Yes, Freiburg is a very nice city, and living in the south of german too. Its the warmest place in Germany, and i think, the post pretty. Its green and spacy. Near France and Swiss…
Greetings from here to ?? maybe Kanada?

Good job,
anke



Anke Brodersen
Grafik und Gestaltung


Mediengenossen eG   
Guntramstr. 11
D-79106 Freiburg
Tel. 0049.(0)761.88869099
www.mediengenossen.de
